### ISSUE TITLE
Chapters begin counting on 2

### ISSUE THREAD

**Issue by elomarns** [fnando/kitabu#20]
I've started a project with Kitabu, and when I exported it, the first chapter was listed as "Chapter 2" instead of "Chapter 1". To be sure I wasn't doing anything wrong, I've created another project, and exported it right away, and the same ocurred: the sample chapter was listed as "Chapter 2".

Tweaking on Firebug, I've found the problem may be on default layout.css (line 121):

``` css
/* =========== */
/* = CHAPTER = */
/* =========== */
#chapters {
    counter-reset: page 1;
    counter-reset: chapter 1;
    page-break-before: always;
}
```

When I've changed the line 121 to "counter-reset: chapter;" (I've just remove the blank space and the "1" character") the chapters was numbered as expected.

I would do a pull request, but I'm not sure I'm not breaking nothing.
