### ISSUE TITLE
Don't add left padding to both `pre` and `pre code`

### ISSUE THREAD

**Issue by nathanl** [fnando/kitabu#42]
The first line of each of my code blocks is indented too far. It looks like this:

![markdown_code_html_output](https://f.cloud.github.com/assets/338814/775712/30f9adf2-e976-11e2-8014-e22b6beb6445.png)

when it should look like this:

![markdown_code_html_output_corrected](https://f.cloud.github.com/assets/338814/775782/4f49ccc8-e977-11e2-8484-968c558c4081.png)

The root issue here is that Markdown specifies that code blocks come out looking like this:

```html
<pre><code>This is a code block.
</code></pre>
```

as opposed to this:

```html
<pre><code>
This is a code block.
</code></pre>
```

The lack of a linebreak causes weirdness. This isn't Kitabu's fault and shouldn't be solved by you; I've got a question about it here:

http://stackoverflow.com/questions/17574489/does-any-markdown-parser-allow-adding-a-linebreak-to-the-start-of-code-blocks

However, one way I can make it look OK is to NOT apply left padding to `pre code` elements. If I change your `layout.css` from this:

```css
pre, pre code {
	font-size: 8pt;
	line-height: 1.4;
	padding-left: 25pt;
}
```

to this:

```css
pre, pre code {
	font-size: 8pt;
	line-height: 1.4;
}

pre {
	padding-left: 25pt;
}
```

... it looks correct.

The `code` element really doesn't need left padding anyway, since its parent `pre` already has it.

Do you see any problem with making this style change?
